
import { Book } from './types';

export const INITIAL_BOOKS: Book[] = [
  {
    id: '1',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '9780743273565',
    description: 'The story of the mysteriously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan.',
    category: 'Classic Fiction',
    publishedDate: '1925-04-10',
    coverImageUrl: 'https://picsum.photos/seed/greatgatsby/400/600',
    tags: ['classic', 'fiction', '1920s'],
  },
  {
    id: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '9780061120084',
    description: 'A novel about the serious issues of rape and racial inequality.',
    category: 'Classic Fiction',
    publishedDate: '1960-07-11',
    coverImageUrl: 'https://picsum.photos/seed/mockingbird/400/600',
    tags: ['classic', 'fiction', 'legal'],
  },
  {
    id: '3',
    title: '1984',
    author: 'George Orwell',
    isbn: '9780451524935',
    description: 'A dystopian novel set in Airstrip One, a province of the superstate Oceania in a world of perpetual war.',
    category: 'Dystopian Fiction',
    publishedDate: '1949-06-08',
    coverImageUrl: 'https://picsum.photos/seed/1984/400/600',
    tags: ['dystopian', 'sci-fi', 'classic'],
  },
  {
    id: '4',
    title: 'Dune',
    author: 'Frank Herbert',
    isbn: '9780441013593',
    description: 'Set in the distant future amidst a feudal interstellar society in which various noble houses control planetary fiefs.',
    category: 'Science Fiction',
    publishedDate: '1965-08-01',
    coverImageUrl: 'https://picsum.photos/seed/dune/400/600',
    tags: ['sci-fi', 'fantasy', 'epic'],
  },
   {
    id: '5',
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    isbn: '9780618260300',
    description: 'The enchanting prequel to The Lord of the Rings, The Hobbit is the story of Bilbo Baggins, a quiet and contented hobbit whose life is turned upside down when he joins the wizard Gandalf and thirteen dwarves on their quest to reclaim their stolen treasure.',
    category: 'Fantasy',
    publishedDate: '1937-09-21',
    coverImageUrl: 'https://picsum.photos/seed/hobbit/400/600',
    tags: ['fantasy', 'adventure', 'classic'],
  },
  {
    id: '6',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '9780141439518',
    description: 'A romantic novel of manners written by Jane Austen in 1813. The novel follows the character development of Elizabeth Bennet, the dynamic protagonist of the book who learns about the repercussions of hasty judgments and comes to appreciate the difference between superficial goodness and actual goodness.',
    category: 'Romance',
    publishedDate: '1813-01-28',
    coverImageUrl: 'https://picsum.photos/seed/prideprejudice/400/600',
    tags: ['classic', 'romance', 'fiction'],
  },
  {
    id: '7',
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    isbn: '9780062316097',
    description: 'A book by Yuval Noah Harari, first published in Hebrew in Israel in 2011 based on a series of lectures Harari taught at The Hebrew University of Jerusalem. The book, focusing on Homo sapiens, surveys human history, starting from the Stone Age and going up to the twenty-first century.',
    category: 'Non-Fiction',
    publishedDate: '2015-02-10',
    coverImageUrl: 'https://picsum.photos/seed/sapiens/400/600',
    tags: ['history', 'non-fiction', 'anthropology'],
  },
  {
    id: '8',
    title: 'The Alchemist',
    author: 'Paulo Coelho',
    isbn: '9780062315007',
    description: 'The story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure. His quest will lead him to riches far different—and far more satisfying—than he ever imagined.',
    category: 'Fantasy',
    publishedDate: '1988-01-01',
    coverImageUrl: 'https://picsum.photos/seed/alchemist/400/600',
    tags: ['fantasy', 'adventure', 'philosophy'],
  }
];
